### ISSUE TITLE
Repo is empty

### ISSUE THREAD

**Issue by dumblob** [pssolanki111/Sci-Calci-GUI#2]
Could it be that you forgot to git-push the scripts?

**Comment by pssolanki111** [comment]
hey @dumblob this was back when I was learning git :D and the project wasn't worth keeping public so I redid the history. I'll probably remove some of my old repos. Thanks for pointing this out though.

My significant work is in private repositories lol. Some contributions to libraries and my own package `polygon` are the only things I can keep public.
